---
- name: install shutter - gcolor2 - silversearcher-ag - vlc
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - shutter
    - gcolor2
    - silversearcher-ag
    - vlc
  sudo: yes

- name: install virtualenvwrapper
  pip:
    name: virtualenvwrapper
  sudo: yes

- name: download fixubuntu
  get_url:
    url: https://raw.githubusercontent.com/sans-dfir/sift-files/master/fixubuntu.sh
    dest: "{{ ansible_env.HOME }}/setup/fixubuntu.sh"
    mode: 0755

- name: run fixubuntu
  command: "{{ ansible_env.HOME }}/setup/fixubuntu.sh"
  sudo: true

- name: enable workspaces - two horizontal
  gsettings:
    schema: org.compiz.core:/org/compiz/profiles/unity/plugins/core/
    key: hsize
    int: 2

- name: enable workspaces - two vertical
  gsettings:
    schema: org.compiz.core:/org/compiz/profiles/unity/plugins/core/
    key: vsize
    int: 2

- name: download steam
  get_url:
    url: https://steamcdn-a.akamaihd.net/client/installer/steam.deb
    dest: "{{ ansible_env.HOME }}/setup/steam.deb"
    mode: 0755

- name: accept steams licencing agreement - purge
  command: 'echo "steam steam/purge note" | sudo debconf-set-selections'
  sudo: true

- name: accept steams licencing agreement - licence
  command: 'echo "steam steam/license note" | sudo debconf-set-selections'
  sudo: true

- name: accept steams licencing agreement - question
  command: 'echo "steam steam/question select I AGREE" | sudo debconf-set-selections '
  sudo: true

- name: install steam
  apt:
    deb: "{{ ansible_env.HOME }}/setup/steam.deb"
  sudo: yes
