---
- name: horse vim - download vim
  apt:
    name: vim
    update_cache: yes
  sudo: yes

- name: horse vim - make sure vim automload directory exists
  file:
    path: "{{ ansible_env.HOME }}/.vim/autoload"
    state: directory
    mode: 0777
  sudo: yes

- name: horse vim - make sure nvim config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    state: directory
    mode: 0777
  sudo: yes

- name: horse vim - get vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
    mode: 0755

- name: horse vim - get vim-plug for neovim
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
    mode: 0755

- name: horse vim - checkout repo
  git:
    repo: https://github.com/JBKahn/horse.vim.git
    dest: "{{ ansible_env.HOME }}/horse.vim"

- name: horse vim - copy .vimrc file
  file:
    src: "{{ ansible_env.HOME }}/horse.vim/.vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: 0755
    state: link

- name: horse vim - copy .vimrc.bundles file
  file:
    src: "{{ ansible_env.HOME }}/horse.vim/.vimrc.bundles"
    dest: "{{ ansible_env.HOME }}/.vimrc.bundles"
    mode: 0755
    state: link

- name: horse vim - make sure vim colors directory exists
  file:
    path: "{{ ansible_env.HOME }}/.vim/colors"
    state: directory
    mode: 0777
  sudo: yes

- name: horse vim - copy color to config to avoid error
  copy:
    src: base16-monokai.vim
    dest: "{{ ansible_env.HOME }}/.vim/colors/base16-monokai.vim"
    mode: 0755

# Commented out since Neovim bug causes it not to close.
# - name: horse vim - run PlugInstall
#   command: vim +PlugInstall +qall

- name: horse vim - add NeoVim ppa
  apt_repository:
    repo: 'ppa:rudenko/neovim'
    state: present
    update_cache: yes
  sudo: yes

- name: horse vim - install neovim
  apt:
    name: neovim
    update_cache: yes
  sudo: yes

- name: horse vim - symlink nvimrc
  file:
    src: "{{ ansible_env.HOME }}/horse.vim/.vimrc"
    dest: "{{ ansible_env.HOME }}/~/.config/nvim/init.vim"
    mode: 0755
    state: link

- name: horse vim - symlink nvim
  file:
    src: "{{ ansible_env.HOME }}/.vim"
    dest: "{{ ansible_env.HOME }}/.nvim"
    mode: 0755
    state: link
