---
- name: download vagrant .deb package
  get_url: url={{ vagrant_url }} dest=/home/{{ username }}/setup/vagrant.deb mode=0755

- name: install vagrant
  apt: deb=/home/{{ username }}/setup/vagrant.deb
  sudo: yes

- name: download virtualbox .deb package
  get_url: url={{ virtualbox_url }} dest=/home/{{ username }}/setup/virtualbox.deb mode=0755

- name: install virtualbox
  apt: deb=/home/{{ username }}/setup/virtualbox.deb
  sudo: yes

- name: install wave dependencies
  apt: name="{{ item }}" state=installed update_cache=yes
  with_items:
    - python-pip
    - curl
    - nodejs
    - nfs-kernel-server
    - nfs-common
    - rpcbind
    - tmux
    - npm
  sudo: yes

- name: install global nodejs packages
  npm:
    name: "{{ item.name }}"
    state: present
    global: yes
    version: "{{ item.version|default('') }}"
  with_items:
    - {name: 'bower'}
    - {name: 'coffee-script', version: '1.7.1'}
    - {name: 'grunt-cli'}
    - {name: 'less'}
    - {name: 'jshint'}
    - {name: 'coffee-jshint'}
  sudo: yes

- name: install tmuxp
  pip: name=tmuxp
  sudo: yes

- name: copy tmuxp config
  copy: src=.tmux.conf dest=/home/{{ username }}/.tmux.conf mode=0755
